---
- hosts: websever
  become: yes
  vars:
    build_number: '{{ BUILD_NUMBER }}'
  #become_user: tomcat
  tasks:

  - name: create directory 
    file:
      path: /home/ec2-user/sourcefile
      state: directory
      mode: 0777

  - name: download war file
    ansible.builtin.get_url:
      url: https://vina.jfrog.io/artifactory/pay_war-generic-local/appB/webapp-{{ build_number }}.war
      dest: /home/ec2-user/sourcefile/webapp.war
      username: vinaykh2015@gmail.com
      password: Vinay@123

  - name: create directory with a date in name
    file: 
      path: /home/ec2-user/backup
      state: directory
      mode: 0777

  - name: backup file with owner and permissions
    copy:
      src: /home/ec2-user/apache-tomcat-9.0.96/webapps/webapp.war
      dest: /home/ec2-user/backup/webapp.war
      remote_src: yes

  - name: Delete remote war file
    file:
      path: /home/ec2-user/apache-tomcat-9.0.96/webapps/webapp.war
      state: absent

  - name: deploy file with owner and permissions
    copy:
      src: /home/ec2-user/sourcefile/webapp.war
      dest: /home/ec2-user/apache-tomcat-9.0.95/webapps/webapp.war
      remote_src: yes
